sudo: false

language:
    - php
    - node_js

php:
#    - 5.4
    - 5.5

node_js:
    - 0.12.5

env:
#    - WP_VERSION=latest WP_MULTISITE=0
#    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
#    - WP_VERSION=4.0 WP_MULTISITE=1

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - source $DEV_LIB_PATH/travis.before_script.sh

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist
    - $DEV_LIB_PATH/travis.script.sh

after_script:
    - $DEV_LIB_PATH/travis.after_script.sh
